[build]
  base = "frontend"
  publish = "build"
  command = "pip install --upgrade pip && cd .. && pip install -r requirements.txt && cd frontend && npm run build"

[build.environment]
  PYTHON_VERSION = "3.9"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
