services:
  - type: web
    name: rag2-backend
    env: docker
    plan: free
    region: oregon
    dockerfilePath: ./Dockerfile
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PYTHONUNBUFFERED
        value: 1
    healthCheckPath: /api/status
